### ISSUE TITLE
index.html could not be copied to 404.html. Continuing without an error.

### ISSUE THREAD

**Issue by pratik-bali** [angular-schule/angular-cli-ghpages#41] opened 2018-06-16 07:56 UTC
`ngh --dir dist/third`
`sudo angular-cli-ghpages --branch gh-pages`
`angular-cli-ghpages`
index.html could not be copied to 404.html. Continuing without an error.
An error occurred!
 Error: Unspecified error (run without silent option for detail)
then i tried
` sudo npm run deploy`
then it says successfully published
with error listed above

**Comment by dyh333** [comment] 2018-06-26 09:07
+1

**Comment by JohannesHoppe** [comment] 2018-07-20 07:23
Duplicate of #37, use `--dir` until I figured out an automated detection of the right folder.

**Closed by JohannesHoppe** 2018-07-20 07:23 UTC

**Comment by Atekawere** [comment] 2020-04-14 05:50
npx angular-cli-ghpages --dir=dist/Git-Search
index.html could not be copied to 404.html. This does not look like an angular-cli project?!
(Hint: are you sure that you have setup the directory correctly?)
Diagnostic info: ENOENT: no such file or directory, stat '/home/victor/Desktop/Git-Search/Git/dist/Git-Search/index.html'
👨🚀 Uploading via git, please wait...
❌ An error occurred when trying to deploy:
ENOENT: no such file or directory, stat '/home/victor/Desktop/Git-Search/Git/dist/Git-Search'
 
Getting this error which i dont understand

**Comment by JohannesHoppe** [comment] 2020-04-14 05:53
Please use the new `ng deploy` (see README) command which determines the right folder!
