### ISSUE TITLE
No commit is made to repo, but ngh prints `Successfully published!`

### ISSUE THREAD

**Issue by Shivakishore14** [angular-schule/angular-cli-ghpages#33] opened 2018-01-21 12:03 UTC
### this is what i used
```
$ sudo ngh --branch=master --repo=https://github.com/Code-Freaks/Code-Freaks.github.io.git -S
Password:
Cloning https://github.com/Code-Freaks/Code-Freaks.github.io.git into ../../../../usr/local/lib/node_modules/angular-cli-ghpages/node_modules/gh-pages/.cache

Cleaning

Fetching origin

Checking out origin/master

Removing files

Copying files

Adding all

Committing

Pushing

Successfully published!
```
but no commits are made to the master branch

**Comment by JohannesHoppe** [comment] 2018-01-21 12:09
Check the remote repository again. You won't see local changes.

As you see in the logs, a fresh copy is cloned to `.cache`. Changes are applied to the new clone and everything committed and pushed to the remote only. This is by design.

Cheers! 😄

**Closed by JohannesHoppe** 2018-01-21 12:09 UTC

**Comment by Shivakishore14** [comment] 2018-01-21 16:26
Sry for not making the problem clear.
I looked at the github repo also the last commit was made hours ago.
and the commits where not showing up in the `commits` section of the repo either.
