### ISSUE TITLE
CORS error when requesting dist files from goDaddy.

### ISSUE THREAD

**Issue by alphatier826** [angular-schule/angular-cli-ghpages#165] opened 2023-04-02 15:52 UTC
![image](https://user-images.githubusercontent.com/91086640/229363957-d4e6b0d0-16bb-4ea6-ae1e-543a17900ce8.png)

The above image shows the CORS issue while my custom domain website tries to consume dist files from GitHub ghPage.
Below is the command I use after pushing the code in GitHub - 

ng build --prod --base-href "github_project_path" --source-map --build-optimizer

ngh --dir dist/AHMv2

The custom domain configuration is also getting success. 
![image](https://user-images.githubusercontent.com/91086640/229364101-f7248f21-ed40-4047-87dc-cb4cd9721d3b.png)

**Comment by fmalcher** [comment] 2023-04-02 16:25
When you run the app at the root of your domain there is no need to set the base-href to a different value.
Can you access the bundle files directly in the browser?
Please also check whether the bundles are correctly pushed to the repo. If this happens, the problem is beyond the scope of this lib.

**Comment by alphatier826** [comment] 2023-04-02 16:40
@fmalcher 
When you run the app at the root of your domain there is no need to set the base-href to a different value - **Let me try with this.**

Can you please post the exact build command - 
       **ng build --prod --base-href "https://alphatier826.github.io/almighty/"**

Can you access the bundle files directly in the browser?
  **Yes**

Please also check whether the bundles are correctly pushed to the repo. If this happens, the problem is beyond the scope of this lib.
**Please PFA and you can access the below repo.**
![image](https://user-images.githubusercontent.com/91086640/229366596-7a6b1173-7f41-4ca8-a1f5-2d61c7ac1dec.png)

https://github.com/alphatier826/almighty/tree/gh-pages

**Comment by alphatier826** [comment] 2023-04-02 16:45
@fmalcher 
I ran the command without base-href, and it's throwing the error.

ng build --prod  "https://alphatier826.github.io/almighty/"
![image](https://user-images.githubusercontent.com/91086640/229366819-9466aee2-add8-40cb-8878-a2c082c5d0cb.png)

**Comment by fmalcher** [comment] 2023-04-02 16:48
The command makes no sense now. 😅 You removed the base-href param but not its value. Just create a prod build without any reference to the GitHub repo.

Btw, if somehow possible, I recommend to use the builder version of this library.

Closing this for now as it's not an issue related to the library itself.

**Closed** 2023-04-02 16:48 UTC

**Comment by alphatier826** [comment] 2023-04-02 16:52
@fmalcher 
What does this mean **"I recommend to use the builder version of this library."**, please send me some refrence of this.Or any video clip.

**Comment by fmalcher** [comment] 2023-04-02 16:54
The README explains all of it in detail. We provide a deployment builder that can be used directly from the Angular CLI. It does build and deployment in one command so there's less confusion about the exact two commands needed.

**Comment by alphatier826** [comment] 2023-04-02 16:56
Thanks, It worked. @fmalcher Hidden Superheroes.
