### ISSUE TITLE
Must create gh-pages branch prior to deploying

### ISSUE THREAD

**Issue by fireflysemantics** [angular-schule/angular-cli-ghpages#89] opened 2020-01-05 23:17 UTC
Hi,

If I create a new repository and deploy to it without first initializing the gh-pages branch and set it to be the `gh-pages` "Choice" the deployment does not work.

I documented it here:
https://stackoverflow.com/questions/59596143/angular-app-not-picked-up-by-github-pages

And here:
https://stackoverflow.com/questions/59593032/github-pages-does-not-see-cname-or-setup-ssl

Just curious whether you are seeing this on your end.  As long as I initialize `gh-pages` with for exampe an `index.html` file, everythign works fine.

**Comment by JohannesHoppe** [comment] 2020-01-05 23:44
I can confirm that Github Pages is sometimes a bit choosy at the beginning. I never found out what the problem is. If the problem occurs, you can also simply modify a file via the web interface (e.g. add a space to `index.html`) and commit the change.

I do not see this behavior of github pages as an error of angular-cli-ghpages. So I will close the issue now.

**Closed by JohannesHoppe** 2020-01-05 23:44 UTC

**Comment by oleersoy** [comment] 2020-01-06 15:58
Hi,
I got a reply from Github Pages support about this.  

I was doing the push as a non admin user, and this causes the pages not to get built.  The push has to be done by an admin user.  

Might be good to have something in the docs about the user running the command having admin privileges.

Cheers,
Ole

**Comment by JohannesHoppe** [comment] 2020-01-06 18:27
No, that can't be true. We have an account that only gets "Write” privileges.

We never use admin rights....


<img width="759" alt="Screen Shot 2020-01-06 at 19 26 07" src="https://user-images.githubusercontent.com/640639/71839017-831d3080-30ba-11ea-91cb-2700049509b5.png">
