### ISSUE TITLE
ProcessError: fatal: could not create work tree dir, Permission denied

### ISSUE THREAD

**Issue by gkucmierz** [angular-schule/angular-cli-ghpages#9] opened 2017-02-19 13:30 UTC
```sh
MacBook-Pro-gkucmierz:coin-tools gkucmierz$ ngh --no-silent
Cloning git@github.com:gkucmierz/coin-tools.git into ../../../../usr/local/lib/node_modules/angular-cli-ghpages/node_modules/gh-pages/.cache

An error occurred!

(node:17668) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ProcessError: fatal: could not create work tree dir '../../../../usr/local/lib/node_modules/angular-cli-ghpages/node_modules/gh-pages/.cache': Permission denied
```

**Comment by JohannesHoppe** [comment] 2017-02-19 20:13
>  ProcessError: fatal: could not create work tree dir '../../../../usr/local/lib/node_modules/angular-cli-ghpages/node_modules/gh-pages/.cache': Permission denied

Hmmm... strange.`I'm not on a Mac, so I can't reproduce. 
The `.cache` directory does not have the write/create permission to create the repo.

Please try this as a quick workaround:
`sudo chown -R **yourusername** /usr/local/lib/node_modules/angular-cli-ghpages/node_modules/gh-pages/.cache`
(as seen here http://stackoverflow.com/a/23151665/2042765)

**Comment by JohannesHoppe** [comment] 2017-02-19 20:13
@fmalcher can you kick in, when you have some spare time?

**Comment by JohannesHoppe** [comment] 2017-02-19 20:39
see also https://github.com/tschaub/gh-pages/issues/118

**Comment by JohannesHoppe** [comment] 2017-02-19 20:42
wo could also include the `--clone` command parameter, to avoid this at all https://github.com/tschaub/gh-pages#optionsclone

**Comment by gkucmierz** [comment] 2017-02-20 03:23
Thank you!
Looks like this one worked for me:
```sh
sudo chown -R **yourusername** /usr/local/lib/node_modules/angular-cli-ghpages/node_modules/gh-pages/
```

**Comment by JohannesHoppe** [comment] 2017-05-21 12:27
Fixed in `gh-pages`, see https://github.com/nkbt/react-works/commit/7b0a9e0ad9d92e92d2c3667cbb21c85e276bcb99 and https://github.com/tschaub/gh-pages/issues/118

TODO: test & update new version of `gh-pages`

**Comment by MurhafSousli** [comment] 2017-07-24 12:35
@gkucmierz `sudo ngh` worked for me

**Comment by tomGdow** [comment] 2017-09-16 19:44
`sudo chown -R **username"" /usr/lib/node_modules/angular-cli-ghpages/node_modules/gh-pages/`

also worked for me (Angular 4). Thanks!

**Comment by JohannesHoppe** [comment] 2018-08-04 12:43
I tested this out on CircleCI 2.0 and it works flawlessly via npx. (Nodejs 8 or higher required)
No `sudo` required.

```
npm i angular-cli-ghpages --save-dev
npx ngh [OPTIONS]
```

**Closed by JohannesHoppe** 2018-08-04 12:43 UTC
Labels: bug, low-prio

**Comment by DIPCHANDAN** [comment] 2020-07-20 07:29
atal: could not create work tree dir '/usr/share/doc/hacktronian': Permission denied

**Comment by megaton47** [comment] 2020-12-31 21:35
Try changing the directories
